# Generated by Django 5.1.6 on 2025-04-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='owner',
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
